## 什么是PyTorch
PyTorch是基于Python的科学计算类库，主要有以下两个方面的应用：

1、作为Numpy的替代者，充分利用GPU的计算能力。

2、提供一个灵活、快速的深度学习平台。

### 使用conda安装，不支持python2.7,cudanone就是CPU版本的
|版本|命令|
|-|-|
|conda,cuda8,python3.5|conda install pytorch -c pytorch|
|conda,cuda9.0,python3.5|conda install pytorch cuda90 -c pytorch|
|conda,cuda9.1,python3.5|conda install pytorch cuda91|
|conda,cudanone,python3.5|conda install pytorch-cpu -c pytorch|
|conda,cuda8,python3.6|conda install pytorch -c pytorch|
|conda,cuda9.0,python3.6|conda install pytorch cuda90 -c pytorch|
|conda,cuda9.1,python3.6|conda install pytorch cuda91 -c pytorch|
|conda,cudanone,python3.6|conda install pytorch-cpu -c pytorch|

### 使用pip安装，不支持python2.7,cudanone就是CPU版本的
|版本|命令|
| :-: | :-: |
pip,cudanone,python3.5|pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp35-cp35m-win_amd64.whl
pip,cuda8,python3.5|pip3 install http://download.pytorch.org/whl/cu80/torch-0.4.0-cp35-cp35m-win_amd64.whl
pip,cuda9.0,python3.5|pip3 install http://download.pytorch.org/whl/cu90/torch-0.4.0-cp35-cp35m-win_amd64.whl
pip,cuda9.1,python3.5|pip3 install http://download.pytorch.org/whl/cu91/torch-0.4.0-cp35-cp35m-win_amd64.whl
pip,cudanone,python3.6|pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-win_amd64.whl
pip,cuda8,python3.6|pip3 install http://download.pytorch.org/whl/cu80/torch-0.4.0-cp36-cp36m-win_amd64.whl
pip,cuda9.0,python3.6|pip3 install http://download.pytorch.org/whl/cu90/torch-0.4.0-cp36-cp36m-win_amd64.whl
pip,cuda9.1,python3.6|pip3 install http://download.pytorch.org/whl/cu91/torch-0.4.0-cp36-cp36m-win_amd64.whl

In [2]:
from __future__ import print_function
import torch

In [2]:
# 构建一个5*3的未初始化的矩阵
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  2.1019e-44],
        [ 0.0000e+00,  2.3669e+21,  5.4931e-43],
        [ 3.1256e+22,  5.4931e-43,  0.0000e+00],
        [ 0.0000e+00,  2.1019e-44,  0.0000e+00],
        [ 2.5439e+21,  5.4931e-43,  3.1256e+22]])


In [3]:
# 构建一个随机初始化的矩阵
y = torch.rand(5,3)
print(y)

tensor([[ 0.8088,  0.2708,  0.8338],
        [ 0.4834,  0.9943,  0.7922],
        [ 0.4358,  0.9478,  0.9259],
        [ 0.4389,  0.9349,  0.8229],
        [ 0.8208,  0.8066,  0.2267]])


In [4]:
# 构建一个元素类型为long且元素值为0的矩阵
z = torch.zeros(5,3,dtype=torch.long)
print(z)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [5]:
# 构建一个直接加载数据的矩阵
t = torch.tensor([[3.3,12],[3,5]])
print(t)

tensor([[  3.3000,  12.0000],
        [  3.0000,   5.0000]])


In [8]:
# 获得矩阵的size，torch.size实际是tuple，它支持tuple所有的运算。
print(t.size())

torch.Size([2, 2])


In [10]:
# 基于现有的tensor来建立一个tensor。这个方法将复用源tensor的属性（如：dtype等），除非知道提供一个新的值
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.5455,  1.5704,  0.6647],
        [-1.5114,  0.8230, -1.3013],
        [ 0.1714,  0.1366,  0.0819],
        [ 0.6514,  0.0445, -0.6827],
        [ 0.3872,  1.9244, -1.6920]])


## 运算

### 加法：

In [7]:
# 语法1
print(x+y)

tensor([[ 8.0885e-01,  2.7076e-01,  8.3376e-01],
        [ 4.8337e-01,  4.7339e+21,  7.9224e-01],
        [ 6.2513e+22,  9.4777e-01,  9.2587e-01],
        [ 4.3891e-01,  9.3494e-01,  8.2290e-01],
        [ 5.0878e+21,  8.0661e-01,  6.2513e+22]])


In [6]:
# 语法2
print(torch.add(x,y))

tensor([[ 8.0885e-01,  2.7076e-01,  8.3376e-01],
        [ 4.8337e-01,  4.7339e+21,  7.9224e-01],
        [ 6.2513e+22,  9.4777e-01,  9.2587e-01],
        [ 4.3891e-01,  9.3494e-01,  8.2290e-01],
        [ 5.0878e+21,  8.0661e-01,  6.2513e+22]])


In [4]:
# 加法：作为输出参数
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 8.0885e-01,  2.7076e-01,  8.3376e-01],
        [ 4.8337e-01,  2.3669e+21,  7.9224e-01],
        [ 3.1256e+22,  9.4777e-01,  9.2587e-01],
        [ 4.3891e-01,  9.3494e-01,  8.2290e-01],
        [ 2.5439e+21,  8.0661e-01,  3.1256e+22]])


In [8]:
# 加法：内联
y.add_(x)
print(y)

tensor([[ 8.0885e-01,  2.7076e-01,  8.3376e-01],
        [ 4.8337e-01,  4.7339e+21,  7.9224e-01],
        [ 6.2513e+22,  9.4777e-01,  9.2587e-01],
        [ 4.3891e-01,  9.3494e-01,  8.2290e-01],
        [ 5.0878e+21,  8.0661e-01,  6.2513e+22]])


In [9]:
# 可以使用标准的类似Numpy的行列索引。
print(x[:1])

tensor(1.00000e-44 *
       [[ 0.0000,  0.0000,  2.1019]])


In [10]:
# 变换大小：如果你想改变调整大小/改造张量，你可以使用 torch.view:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Tensor有包括 转置、索引、切片、数学操作、线性代数、随机数等100多种运算，具体详见[Torch](https://pytorch.org/docs/stable/torch.html#math-operations)

In [11]:
# 如果你有一个一个元素的tensor，可以使用 .item()获得其中的数字。
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 0.3630])
0.36302807927131653


## Numpy Bridge
将Torch Tensor 转换成NumPy 数组，反之亦然。 Torch Tensor和NumPy 数组是共享内存，修改其中一个的值，那么另外一个的值也会改变。

### 将Tensor转换成 NumPy Array

In [3]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [4]:
b= a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [5]:
# 观察numpy array的值会被改变。
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


### 将NumPy Array 转换成Tensor

In [6]:
# 观察numpy array如何自动转换成Torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)
